[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "syntactic_interpretability"
version = "0.0.1"

dependencies = [
    "transformers>=4.34.1",
]